apiVersion: v1
kind: Pod
metadata:
  name: multiarch-nginx
  namespace: multiarch-test
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: singlearch-nginx
  namespace: multiarch-test
spec:
  containers:
  - image: bitnami/nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
---
