apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jeopardy-nodeselector.fullname" . }}
  labels:
    {{- include "jeopardy-nodeselector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jeopardy-nodeselector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jeopardy-nodeselector.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jeopardy-nodeselector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/jeopardy-nodeselector"]
          args:
            [
              "-host=$(HOSTNAME)",
              "-port=8443",
              "-cert-path=/certs/tls.crt",
              "-key-path=/certs/tls.key"
            ]
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
          - name: certs
            readOnly: true
            mountPath: "/certs"
          livenessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: certs
        secret:
          secretName: {{ include "jeopardy-nodeselector.fullname" . }}-certs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
