{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jeopardy-nodeselector.serviceAccountName" . }}
  labels:
{{ include "jeopardy-nodeselector.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jeopardy-nodeselector.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jeopardy-nodeselector.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jeopardy-nodeselector.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jeopardy-nodeselector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
