---
#
# ci/pipeline.yml
#
# Pipeline structure file for a Docker Image pipeline
#
# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
#
# author:  James Hunt <james@niftylogic.com>
#          Dennis Bell <dennis.j.bell@gmail.com>
# created: 2016-03-04

meta:
  name:     (( param "Please name your pipeline" ))
  release:  (( grab meta.name ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  url:      (( param "Please specify the full url of the target Concourse CI" ))
  pipeline: (( grab meta.name ))
  image:    starkandwayne/concourse

  docker:
    dockerfile: "Dockerfile"

  git:
    email:  (( param "Please provide the git email for automated commits" ))
    name:   (( param "Please provide the git name for automated commits" ))

  aws:
    bucket:     (( concat meta.name "-pipeline" ))
    region_name: us-east-1
    access_key: (( param "Please set your AWS Access Key ID" ))
    secret_key: (( param "Please set your AWS Secret Key ID" ))

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch:       master
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
    access_token: (( param "Please generate a Personal Access Token and specify it here" ))

  dockerhub:
    email:      (( param "Please specify the email address for your Dockerhub account" ))
    username:   (( param "Please specify the username for your Dockerhub account" ))
    password:   (( param "Please specify the password for your Dockerhub account" ))
    repository: (( param "Please specify the name of the image (repo/name) that you are building" ))

groups:
  - name: (( grab meta.name ))
    jobs:
      - build
      - promote
      - minor
      - major

jobs:
  - name: build
    public: true
    serial: true
    plan:
      - get: git
        trigger: true
      - put: amd64
        params:
          build:      "git"
          cache:      true
          dockerfile: (( concat "git/" meta.docker.dockerfile ))
      - put: arm64
        params:
          build_args:
            GOARCH: "arm64"
          build:      "git"
          cache:      true
          dockerfile: (( concat "git/" meta.docker.dockerfile ))
      - put: armhf
        params:
          build_args:
            GOARCH: "arm"
            GOARM:  "7"
          build:      "git"
          cache:      true
          dockerfile: (( concat "git/" meta.docker.dockerfile ))

  - name: minor
    public: true
    plan:
      - { get: version, trigger: false, params: {bump: minor} }
      - { put: version,                 params: {file: version/number} }

  - name: major
    public: true
    plan:
      - { get: version, trigger: false, params: {bump: major} }
      - { put: version,                 params: {file: version/number} }

  - name: promote
    public: true
    serial: true
    plan:
      - aggregate:
          - { get: version }
          - { get: edge, passed: [build], params: { save: true } }
          - { get: git,  passed: [build] }

      - task: release
        config:
          image_resource:
            type: docker-image
            source:
              repository: (( grab meta.image ))
          platform: linux
          inputs:
            - name: git
            - name: version
          outputs:
            - name: gh
            - name: pushme
          run:
            path: ./git/ci/scripts/release
            args: []
          params:
            REPO_ROOT:    git
            RELEASE_ROOT: gh
            RELEASE_NAME: (( grab meta.release ))
            REPO_OUT:     pushme/git
            VERSION_FROM: version/number
            GIT_EMAIL:    (( grab meta.git.email ))
            GIT_NAME:     (( grab meta.git.name ))

      - put: latest # as 'latest'
        params:
          load:       edge

      - put: latest # as 'vX.Y.Z'
        params:
          tag:             version/number
          tag_prefix:      v
          load:       edge

      - put: version
        params:
          bump: patch
      - put: git
        params:
          rebase: true
          repository: pushme/git
      - put: github
        params:
          name: gh/name
          tag:  gh/tag
          body: gh/notes.md

resources:
  - name: git
    type: git
    source:
      uri:         (( grab meta.github.uri ))
      branch:      (( grab meta.github.branch ))
      private_key: (( grab meta.github.private_key ))

  - name: amd64
    type: docker-image
    source:
      .: (( inject meta.dockerhub ))
      tag: latest-amd64

  - name: arm64
    type: docker-image
    source:
      .: (( inject meta.dockerhub ))
      tag: latest-arm64

  - name: armhf
    type: docker-image
    source:
      .: (( inject meta.dockerhub ))
      tag: latest-armhf

  - name: version
    type: semver
    source :
      driver:            s3
      bucket:            (( grab meta.aws.bucket ))
      region_name:       (( grab meta.aws.region_name ))
      key:               version
      access_key_id:     (( grab meta.aws.access_key ))
      secret_access_key: (( grab meta.aws.secret_key ))
      initial_version:   (( grab meta.initial_version || "0.0.1" ))

  - name: github
    type: github-release
    source:
      user:         (( grab meta.github.owner ))
      repository:   (( grab meta.github.repo ))
      access_token: (( grab meta.github.access_token ))
