apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: jeopardy-nodeselector-demo
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jeopardy-nodeselector-demo
  namespace: default
spec:
  commonName: jeopardy-nodeselector.default.svc
  secretName: jeopardy-nodeselector-demo-build
  issuerRef:
    name: jeopardy-nodeselector-demo
  usages:
    - server auth
  keySize: 2048
  dnsNames:
  - jeopardy-nodeselector.default.svc
  - jeopardy-nodeselector.default.svc.cluster.local
  - jeopardy-nodeselector.jeopardy-nodeselector.svc
  - jeopardy-nodeselector.jeopardy-nodeselector.svc
  - jeopardy-nodeselector.jeopardy-nodeselector-test.svc.cluster.local
  - jeopardy-nodeselector.jeopardy-nodeselector-test.svc.cluster.local
  - localhost
  - 127.0.0.1
