apiVersion: v1
kind: ServiceAccount
metadata:
  name: jeopardy-nodeselector
  namespace: default
  labels:
    app: jeopardy-nodeselector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jeopardy-nodeselector
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jeopardy-nodeselector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jeopardy-nodeselector
subjects:
- kind: ServiceAccount
  name: jeopardy-nodeselector
  namespace: default
